<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VSJMPEM" failures="1" tests="5" name="Login Test" time="58.195" errors="0" timestamp="2024-02-17T18:35:10 IST">
  <testcase classname="com.testcases.LoginPageTest" name="loginTest" time="2.1"/>
  <testcase classname="com.testcases.LoginPageTest" name="loginTest" time="1.51"/>
  <testcase classname="com.testcases.LoginPageTest" name="loginTest" time="1.67">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at com.testcases.LoginPageTest.loginTest(LoginPageTest.java:43)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.testcases.LoginPageTest" name="loginTest" time="2.083"/>
  <testcase classname="com.testcases.LoginPageTest" name="loginTest" time="2.011"/>
</testsuite> <!-- Login Test -->
